Algoritmo "Fatorialfuncao"

var
 n, f: inteiro
 
 funcao fatorial(v: inteiro) : inteiro
 var
    c, R:inteiro
inicio
      R <-1
      Para C <- 1 ate v faca
           R <- R*c
      fimpara
      retorne R
 fimfuncao
 
 inicio
 
       escreval("Digite um numero: ")
       leia(n)
       
       F <- fatorial(n)
       Escreval("o fatorial de ",n, " ! é igual a : ",f)
 

Fimalgoritmo